-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.category (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  categoryName text NOT NULL UNIQUE,
  image text,
  active boolean,
  description text,
  CONSTRAINT category_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sub_category (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subCategoryName text NOT NULL,
  categoryId uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT sub_category_pkey PRIMARY KEY (id),
  CONSTRAINT sub_category_categoryId_fkey FOREIGN KEY (categoryId) REFERENCES public.category(id)
);
CREATE TABLE public.handyman (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firstName text,
  lastName text,
  email text,
  phoneNumber text,
  password text,
  userName text,
  userType text,
  category text,
  subCategory text,
  profileImage text,
  provider_id uuid DEFAULT gen_random_uuid(),
  fcmToken text,
  countryCode text,
  address text,
  active boolean,
  isActive boolean,
  createdAt timestamp with time zone DEFAULT now(),
  user_id uuid,
  categoryId uuid,
  subCategoryId uuid,
  slug text,
  CONSTRAINT handyman_pkey PRIMARY KEY (id),
  CONSTRAINT handyman_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  request_id uuid,
  bookingId text,
  customerId uuid,
  description text,
  handymanId uuid,
  providerId uuid,
  senderId uuid,
  type text,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_handymanId_fkey FOREIGN KEY (handymanId) REFERENCES public.handyman(id),
  CONSTRAINT notifications_providerId_fkey FOREIGN KEY (providerId) REFERENCES public.provider(id),
  CONSTRAINT notifications_senderId_fkey FOREIGN KEY (senderId) REFERENCES auth.users(id),
  CONSTRAINT notifications_customerid_fkey FOREIGN KEY (customerId) REFERENCES public.customer(id),
  CONSTRAINT notifications_handymanid_fkey FOREIGN KEY (handymanId) REFERENCES public.handyman(id),
  CONSTRAINT notifications_providerid_fkey FOREIGN KEY (providerId) REFERENCES public.provider(id),
  CONSTRAINT notifications_senderid_fkey FOREIGN KEY (senderId) REFERENCES auth.users(id),
  CONSTRAINT notifications_customerId_fkey FOREIGN KEY (customerId) REFERENCES public.customer(id)
);
CREATE TABLE public.provider_analytics (
  id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT provider_analytics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.page_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid,
  date_id date NOT NULL,
  count integer DEFAULT 1,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT page_views_pkey PRIMARY KEY (id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  website text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  provider_id uuid NOT NULL UNIQUE,
  company_name text,
  industry text,
  company_size text,
  headquarters text,
  founded text,
  profile_bio text,
  banner_image text,
  CONSTRAINT companies_pkey PRIMARY KEY (id),
  CONSTRAINT companies_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.provider(id)
);
CREATE TABLE public.opportunities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid,
  title text NOT NULL,
  amount numeric,
  currency text DEFAULT 'USD'::text,
  stage USER-DEFINED NOT NULL DEFAULT 'Lead'::funnel_stage,
  probability integer DEFAULT 10 CHECK (probability >= 0 AND probability <= 100),
  expected_close_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  closed_at timestamp with time zone,
  lost_reason text,
  archived_at timestamp with time zone,
  company_id uuid,
  provider_id uuid NOT NULL,
  note text,
  image text,
  CONSTRAINT opportunities_pkey PRIMARY KEY (id),
  CONSTRAINT opportunities_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.opportunity_stage_history (
  id bigint NOT NULL DEFAULT nextval('opportunity_stage_history_id_seq'::regclass),
  opportunity_id uuid,
  from_stage USER-DEFINED,
  to_stage USER-DEFINED NOT NULL,
  changed_by uuid,
  changed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT opportunity_stage_history_pkey PRIMARY KEY (id),
  CONSTRAINT opportunity_stage_history_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES public.opportunities(id),
  CONSTRAINT opportunity_stage_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  opportunity_id uuid,
  type text CHECK (type = ANY (ARRAY['call'::text, 'email'::text, 'meeting'::text, 'note'::text, 'task'::text])),
  summary text,
  due_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activities_pkey PRIMARY KEY (id),
  CONSTRAINT activities_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES public.opportunities(id),
  CONSTRAINT activities_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.verify_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  createdAt timestamp with time zone NOT NULL,
  providerId uuid NOT NULL,
  providerName text,
  providerEmail text,
  documentId uuid,
  documentImage text,
  isVerify boolean,
  CONSTRAINT verify_documents_pkey PRIMARY KEY (id),
  CONSTRAINT verify_documents_providerId_fkey FOREIGN KEY (providerId) REFERENCES public.provider(id),
  CONSTRAINT verify_documents_documentId_fkey FOREIGN KEY (documentId) REFERENCES public.documents(id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL,
  active boolean NOT NULL,
  name text,
  description text,
  CONSTRAINT documents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  user_email text,
  rating smallint NOT NULL CHECK (rating >= 1 AND rating <= 5),
  type USER-DEFINED NOT NULL,
  message text NOT NULL CHECK (char_length(message) <= 2000),
  screenshot_url text,
  meta jsonb,
  CONSTRAINT feedback_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.job_request (
  id text NOT NULL,
  createdAt timestamp with time zone NOT NULL,
  accepted boolean,
  bidList ARRAY,
  bidPrice text,
  customerId uuid,
  description text,
  handymanId text,
  price text,
  providerId uuid,
  serviceId uuid,
  serviceModelList ARRAY,
  title text,
  status USER-DEFINED DEFAULT 'pending'::feature_request_status_enum,
  is_paid boolean DEFAULT false,
  CONSTRAINT job_request_pkey PRIMARY KEY (id),
  CONSTRAINT job_request_customerId_fkey FOREIGN KEY (customerId) REFERENCES public.customer(id),
  CONSTRAINT job_request_providerId_fkey FOREIGN KEY (providerId) REFERENCES public.provider(id),
  CONSTRAINT job_request_serviceId_fkey FOREIGN KEY (serviceId) REFERENCES public.service(id)
);
CREATE TABLE public.provider (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  email text,
  firstName text,
  lastName text,
  userName text UNIQUE,
  phoneNumber text,
  profileImage text,
  banner text,
  address text,
  country text,
  countryCode text,
  currency text,
  location jsonb CHECK (location IS NULL OR jsonb_typeof(location) = 'object'::text),
  slug text,
  userType text,
  walletAmount text DEFAULT '0'::text,
  active boolean NOT NULL DEFAULT true,
  fcmToken text,
  professionId text,
  categoryId text,
  socialLinks jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof("socialLinks") = 'array'::text),
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  updateAt timestamp with time zone NOT NULL DEFAULT now(),
  password text,
  activation_paid boolean NOT NULL DEFAULT false,
  activation_paid_at timestamp with time zone,
  activation_tx_ref text,
  verified_subcategory_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  archived_at timestamp with time zone,
  provider_type USER-DEFINED DEFAULT 'individual'::provider_type,
  company_verification_status USER-DEFINED DEFAULT 'not_submitted'::company_verification_status,
  company_license_url text,
  company_rejection_reason text,
  service_tier_max integer NOT NULL DEFAULT 0,
  service_tier_paid_at timestamp with time zone,
  service_tier_tx_ref text,
  admin_note text,
  CONSTRAINT provider_pkey PRIMARY KEY (id),
  CONSTRAINT provider_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.customer (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  first_name text NOT NULL,
  last_name text NOT NULL,
  phone text NOT NULL,
  email text,
  country_code text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  address jsonb,
  user_name text,
  profile_pic text,
  fcm_token text,
  login_type text,
  wallet_amount numeric DEFAULT 0,
  active boolean DEFAULT true,
  slug text,
  password text,
  default_address jsonb,
  customer_addresses jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  archived_at timestamp with time zone,
  admin_note text,
  CONSTRAINT customer_pkey PRIMARY KEY (id),
  CONSTRAINT customer_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.service (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  serviceName text NOT NULL,
  description text,
  address text,
  categoryId uuid NOT NULL,
  categoryModel jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof("categoryModel") = 'object'::text),
  subCategoryId uuid NOT NULL,
  subCategoryModel jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof("subCategoryModel") = 'object'::text),
  type text NOT NULL,
  serviceLocationMode text NOT NULL,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  discount text,
  prePayment boolean NOT NULL DEFAULT false,
  feature boolean NOT NULL DEFAULT false,
  status boolean NOT NULL DEFAULT true,
  active boolean DEFAULT true,
  slug text UNIQUE,
  serviceImage ARRAY NOT NULL DEFAULT '{}'::text[],
  likedUser ARRAY,
  reviewCount integer DEFAULT 0 CHECK ("reviewCount" >= 0),
  reviewSum numeric DEFAULT 0,
  location jsonb CHECK (location IS NULL OR jsonb_typeof(location) = 'object'::text),
  position jsonb CHECK ("position" IS NULL OR jsonb_typeof("position") = 'object'::text),
  duration text,
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  isArchived boolean DEFAULT false,
  video text,
  approved boolean NOT NULL DEFAULT false,
  liked_users ARRAY DEFAULT '{}'::uuid[],
  feature_requested_at timestamp with time zone,
  feature_requested_status USER-DEFINED DEFAULT 'none'::feature_request_status_enum,
  CONSTRAINT service_pkey PRIMARY KEY (id),
  CONSTRAINT service_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.provider(id),
  CONSTRAINT service_categoryId_fkey FOREIGN KEY (categoryId) REFERENCES public.category(id),
  CONSTRAINT service_subCategoryId_fkey FOREIGN KEY (subCategoryId) REFERENCES public.sub_category(id)
);
CREATE TABLE public.provider_customer (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  lastBookedAt timestamp with time zone,
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT provider_customer_pkey PRIMARY KEY (id),
  CONSTRAINT provider_customer_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.provider(id),
  CONSTRAINT provider_customer_provider_fkey FOREIGN KEY (provider_id) REFERENCES public.provider(id),
  CONSTRAINT provider_customer_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer(id)
);
CREATE TABLE public.booked_service (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  customer_id uuid,
  provider_user_id uuid,
  customer_user_id uuid,
  service_id uuid,
  serviceName text,
  firstName text NOT NULL,
  lastName text NOT NULL,
  email text,
  phoneNumber text NOT NULL,
  price numeric,
  discount text DEFAULT '0'::text,
  totalAmount numeric DEFAULT 0,
  subTotal numeric DEFAULT 0,
  taxList jsonb NOT NULL DEFAULT '[]'::jsonb,
  quantity integer NOT NULL DEFAULT 1,
  bookingDate timestamp with time zone NOT NULL,
  paymentCompleted boolean NOT NULL DEFAULT false,
  prePaymentExtraChargePayment boolean NOT NULL DEFAULT false,
  postJobPayment boolean NOT NULL DEFAULT false,
  providerMySelf boolean NOT NULL DEFAULT false,
  description text,
  serviceImage text,
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  handyman_id uuid,
  otp text,
  bookingAddress jsonb,
  endTime timestamp with time zone,
  extraChargeAmount text,
  extraChargeGst boolean,
  holdTime ARRAY,
  paymentType text,
  postJob boolean,
  reason text,
  serviceDetails jsonb,
  startTime timestamp with time zone,
  extraChargeModel jsonb,
  coupon text,
  countryCode text,
  adminCommission numeric,
  service_proof jsonb DEFAULT '{}'::jsonb,
  service_proof_updated_at timestamp with time zone DEFAULT now(),
  payment_status USER-DEFINED NOT NULL DEFAULT 'pending_payment'::payment_status_enum,
  payment_id uuid,
  status USER-DEFINED,
  CONSTRAINT booked_service_pkey PRIMARY KEY (id),
  CONSTRAINT booked_service_provider_id_fkey1 FOREIGN KEY (provider_id) REFERENCES public.provider(id),
  CONSTRAINT booked_service_provider_user_id_fkey FOREIGN KEY (provider_user_id) REFERENCES auth.users(id),
  CONSTRAINT booked_service_customer_user_id_fkey FOREIGN KEY (customer_user_id) REFERENCES auth.users(id),
  CONSTRAINT booked_service_handyman_id_fkey FOREIGN KEY (handyman_id) REFERENCES public.handyman(id),
  CONSTRAINT booked_service_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer(id),
  CONSTRAINT booked_service_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.service(id),
  CONSTRAINT booked_service_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.provider_availability_weekly (
  user_id uuid NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  weekly jsonb,
  paw_id uuid,
  CONSTRAINT paw_user_fk FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.provider_blocked_dates (
  id bigint NOT NULL DEFAULT nextval('provider_blocked_dates_id_seq'::regclass),
  user_id uuid NOT NULL,
  blocked_on date NOT NULL CHECK (blocked_on >= CURRENT_DATE),
  reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT provider_blocked_dates_pkey PRIMARY KEY (id),
  CONSTRAINT pbd_user_fk FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.bank_details (
  accountNumber text NOT NULL,
  bankName text,
  branchCity text,
  branchCountry text,
  holderName text,
  providerID uuid DEFAULT gen_random_uuid(),
  swiftCode text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT bank_details_pkey PRIMARY KEY (id),
  CONSTRAINT bank_details_providerID_fkey FOREIGN KEY (providerID) REFERENCES public.provider(id)
);
CREATE TABLE public.wallet_transaction (
  amount text,
  createdDate timestamp with time zone,
  isCredit boolean,
  note text,
  paymentType text,
  transactionId text,
  type text,
  userId uuid,
  provider_id uuid,
  customer_id uuid,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT wallet_transaction_pkey PRIMARY KEY (id),
  CONSTRAINT wallet_transaction_userId_fkey FOREIGN KEY (userId) REFERENCES auth.users(id),
  CONSTRAINT wallet_transaction_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.provider(id),
  CONSTRAINT wallet_transaction_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer(id)
);
CREATE TABLE public.withdrawal_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  adminNote text,
  amount text,
  createdDate timestamp with time zone,
  note text,
  paymentDate text,
  paymentStatus text,
  providerId uuid,
  rejectionReason text,
  CONSTRAINT withdrawal_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.review_customer (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  comment text NOT NULL,
  customerId uuid,
  date timestamp with time zone DEFAULT now(),
  rating text,
  serviceId uuid,
  bookingId uuid,
  CONSTRAINT review_customer_pkey PRIMARY KEY (id),
  CONSTRAINT review_customer_customerId_fkey FOREIGN KEY (customerId) REFERENCES public.customer(id),
  CONSTRAINT review_customer_serviceId_fkey FOREIGN KEY (serviceId) REFERENCES public.service(id),
  CONSTRAINT review_customer_bookingId_fkey FOREIGN KEY (bookingId) REFERENCES public.booked_service(id)
);
CREATE TABLE public.currencies (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  active boolean NOT NULL,
  createdAt timestamp with time zone DEFAULT now(),
  decimalDigits text,
  name text,
  symbol text,
  symbolAtRight boolean,
  CONSTRAINT currencies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.languages (
  active boolean,
  code text,
  name text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT languages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chat (
  chatID text NOT NULL,
  type text,
  senderId text NOT NULL,
  receiverId text NOT NULL,
  message text,
  mediaUrl text,
  seen boolean DEFAULT false,
  timestamp timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_pkey PRIMARY KEY (chatID)
);
CREATE TABLE public.chat_inbox (
  id text NOT NULL,
  lastMessage text,
  mediaUrl text,
  senderId text NOT NULL,
  receiverId text NOT NULL,
  seen boolean DEFAULT false,
  type text DEFAULT 'text'::text,
  timestamp timestamp with time zone DEFAULT now(),
  archive boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_inbox_pkey PRIMARY KEY (id)
);
CREATE TABLE public.customer_service_details (
  id uuid NOT NULL,
  customer_service_id uuid,
  address text,
  category_id text,
  category_name text,
  category_active boolean,
  category_image text,
  category_model_id text,
  create_at timestamp with time zone,
  description text,
  discount text,
  duration text,
  feature jsonb,
  liked_user jsonb,
  location_latitude double precision,
  location_longitude double precision,
  position_geohash text,
  position_geopoint jsonb,
  pre_payment boolean,
  price double precision,
  provider_id text,
  review_count double precision,
  review_sum double precision,
  service_images ARRAY,
  service_name text,
  status text,
  sub_category_id text,
  sub_category_model jsonb,
  type text,
  CONSTRAINT customer_service_details_pkey PRIMARY KEY (id)
);
CREATE TABLE public.customers_service (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customers_service_pkey PRIMARY KEY (id),
  CONSTRAINT customers_service_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer(id)
);
CREATE TABLE public.notification (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  customer_id uuid,
  description text,
  handyman_id uuid,
  provider_id uuid,
  sender_id uuid,
  title text,
  type text,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  action_url text,
  recipient_role text NOT NULL DEFAULT 'admin'::text,
  CONSTRAINT notification_pkey PRIMARY KEY (id),
  CONSTRAINT notification_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.booked_service(id),
  CONSTRAINT notification_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer(id),
  CONSTRAINT notification_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.provider(id),
  CONSTRAINT notification_handyman_id_fkey FOREIGN KEY (handyman_id) REFERENCES public.handyman(id),
  CONSTRAINT notification_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id)
);
CREATE TABLE public.country_tax (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  active boolean DEFAULT false,
  country text,
  isFix boolean DEFAULT false,
  name text,
  value numeric,
  type text,
  CONSTRAINT country_tax_pkey PRIMARY KEY (id)
);
CREATE TABLE public.banner (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  bannerName text,
  image text,
  link text,
  CONSTRAINT banner_pkey PRIMARY KEY (id)
);
CREATE TABLE public.coupon (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  active boolean,
  amount numeric,
  code text,
  expiredAt timestamp with time zone,
  isPrivate boolean,
  isFix boolean,
  title text,
  minAmount numeric,
  CONSTRAINT coupon_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sub_category_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subCategoryId uuid NOT NULL,
  documentId uuid NOT NULL,
  isRequired boolean DEFAULT true,
  description text,
  CONSTRAINT sub_category_documents_pkey PRIMARY KEY (id),
  CONSTRAINT sub_category_documents_subCategoryId_fkey FOREIGN KEY (subCategoryId) REFERENCES public.sub_category(id),
  CONSTRAINT sub_category_documents_documentId_fkey FOREIGN KEY (documentId) REFERENCES public.documents(id)
);
CREATE TABLE public.app_settings (
  id text NOT NULL,
  data jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT app_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid,
  customer_id uuid NOT NULL,
  amount numeric NOT NULL,
  currency text DEFAULT 'ETB'::text,
  status USER-DEFINED NOT NULL DEFAULT 'pending_payment'::payment_status_enum,
  payment_method text,
  provider text,
  provider_ref text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer(id),
  CONSTRAINT payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.booked_service(id)
);
CREATE TABLE public.provider_payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  providerID uuid NOT NULL,
  method_type text NOT NULL DEFAULT 'bank'::text,
  method_code text NOT NULL,
  method_name text NOT NULL,
  holderName text,
  accountNumber text,
  swiftCode text,
  bankName text,
  branchCity text,
  branchCountry text,
  is_active boolean NOT NULL DEFAULT true,
  is_default boolean NOT NULL DEFAULT false,
  currency text NOT NULL DEFAULT 'ETB'::text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT provider_payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT provider_payment_methods_providerID_fkey FOREIGN KEY (providerID) REFERENCES public.provider(id)
);
CREATE TABLE public.contact_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text NOT NULL,
  subject text NOT NULL DEFAULT 'contact'::text,
  message text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contact_messages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  full_name text,
  role text NOT NULL DEFAULT 'viewer'::text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_pkey PRIMARY KEY (id),
  CONSTRAINT admin_role_fkey FOREIGN KEY (role) REFERENCES public.admin_role(slug),
  CONSTRAINT admin_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.admin_role (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  permissions ARRAY NOT NULL DEFAULT '{}'::text[],
  is_system boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_role_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_tier_payment (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id text NOT NULL,
  user_id text NOT NULL,
  from_tier_max integer NOT NULL DEFAULT 0,
  to_tier_max integer NOT NULL,
  amount numeric NOT NULL,
  tx_ref text NOT NULL UNIQUE,
  chapa_status text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT service_tier_payment_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_activity_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  admin_id uuid,
  admin_email text,
  admin_name text,
  admin_role text,
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id text,
  route text,
  summary text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  env text NOT NULL DEFAULT 'prod'::text,
  CONSTRAINT admin_activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT admin_activity_log_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.admin(id)
);