export interface ProviderSchema {
  id: string;
  user_id?: string;
  name?: string;
  firstName?: string;
  lastName?: string;
  first_name?: string;
  last_name?: string;
  email?: string;
  userName?: string;
  phone?: string;
  phoneNumber?: string;
  bannerImage?: string;
  companyName?: string;
  industry?: string;
  companySize?: string;
  headquarters?: string;
  founded?: string;
  address?: string;
  country?: string;
  countryCode?: string;
  country_code?: string;
  currency?: string;
  location?: Record<string, unknown> | null;
  profileBio?: string;
  slug?: string;
  userType?: string;
  walletAmount?: string;
  active?: boolean;
  fcmToken?: string;
  professionId?: string;
  categoryId?: string;
  socialLinks?: Record<string, unknown> | null;
  createdAt?: string;
  created_at?: string;
  updateAt?: string;
  password?: string;
  profileImage?: string;
  profile_image?: string;
  avatar_url?: string;
  banner?: string | null;
  activation_paid?: boolean;
  activation_paid_at?: string;
  activation_tx_ref?: string;
  archived_at?: string | null;
}
