-- Marketing tracker seed data
INSERT INTO public.marketing_tracker_column (key, label, column_type, position, is_system) VALUES
  ('business_name', 'Business Name', 'text', 1, true),
  ('business_type', 'Business Type', 'text', 2, true),
  ('are_trainers', 'Are Trainers?', 'boolean', 3, true),
  ('address', 'Address', 'text', 4, true),
  ('phone', 'Phone', 'text', 5, true),
  ('assignee', 'Assignee', 'text', 6, true),
  ('contact_date', 'Contact Date', 'date', 7, true),
  ('follow_up_date', 'Follow Up Date', 'date', 8, true),
  ('point_of_contact', 'Point of Contact', 'text', 9, true),
  ('contacted', 'Contacted', 'boolean', 10, true),
  ('onboarded', 'Onboarded', 'boolean', 11, true),
  ('coupon', 'Coupon', 'text', 12, true),
  ('note', 'Note', 'text', 13, true)
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.marketing_tracker_row (position, values) VALUES
  (1, $json${"business_name":"EVtopia Car Maitainance Training Institute","business_type":"Automobile Maintainance","address":"Gotera","phone":"09 68 77 77 99"}$json$::jsonb),
  (2, $json${"business_name":"Misael Carpentry","business_type":"Carpentry","address":"Kazanchis Around ECA","phone":"09 13 63 10 33"}$json$::jsonb),
  (3, $json${"business_name":"4 U Catering and Decor","business_type":"Catering","address":"Megenagna","phone":"09 12 77 24 64","assignee":"Hana","contact_date":"2026-06-30"}$json$::jsonb),
  (4, $json${"business_name":"የኛ ገበታ catering & food service","business_type":"Catering","phone":"919387932"}$json$::jsonb),
  (5, $json${"business_name":"Kuku's ኩሽና","business_type":"Catering","address":"Bole, Addis Ababa","phone":"961607813","assignee":"Admas","contact_date":"2026-06-30","contacted":true,"note":"Met the owner and gave her an explanation. She asked about how many users we have, I told her we have acquired 1K+ users in a month. She couldn't install the app at the spot since she was busy. She told me I follow-up her on phone and telegram."}$json$::jsonb),
  (6, $json${"business_name":"Amaziya Event & Catering","business_type":"Catering","phone":"905399957"}$json$::jsonb),
  (7, $json${"business_name":"chefs catering addis","business_type":"Catering","phone":"0920163304 /0913993406 /0710993406"}$json$::jsonb),
  (8, $json${"business_name":"lulu events and catering","business_type":"Catering","phone":"922780651"}$json$::jsonb),
  (9, $json${"business_name":"Apple Catering","business_type":"Catering","phone":"911065034"}$json$::jsonb),
  (10, $json${"business_name":"Deluxe Catering Addis","business_type":"Catering","phone":"979986444"}$json$::jsonb),
  (11, $json${"business_name":"Shine Catering Ethiopia","business_type":"Catering","address":"Bole Medhaniyalem Morning Star Mall 3rd floor","phone":"0911409797 / 0951733333 / 0951833333","assignee":"Admas","contact_date":"2026-06-30","contacted":true,"note":"Met the receptionist and explained to her. She promised to let the owners know that I came. She gave me their business card too."}$json$::jsonb),
  (12, $json${"business_name":"Daily Catering In Addis Ababa","business_type":"Catering","address":"Megenegna, Hayahulet, Kazanchis","phone":"09 43 44 66 02","assignee":"Hana","contact_date":"2026-06-30"}$json$::jsonb),
  (13, $json${"business_name":"Diamond sweet catering","business_type":"Catering","phone":"914646765"}$json$::jsonb),
  (14, $json${"business_name":"Halal catering","business_type":"Catering","phone":"962535455"}$json$::jsonb),
  (15, $json${"business_name":"KT Foods Catering","business_type":"Catering","phone":"0988193386 / 0927171767"}$json$::jsonb),
  (16, $json${"business_name":"Jennah Halal catering","business_type":"Catering","phone":"913976363"}$json$::jsonb),
  (17, $json${"business_name":"Koti Sweet","business_type":"Catering","address":"Bole Alemnesh Plaza 5th Floor","phone":"09 66 72 65 94","assignee":"Admas","contact_date":"2026-06-30","contacted":true,"note":"Met the manager and explained our services. She requested me to send her some videos and our social media and I sent her. She needs to discuss with her peers before getting onboarded."}$json$::jsonb),
  (18, $json${"business_name":"Culinary Institute of Ethiopia","business_type":"Cooking Training","address":"Megenagna, Maraton Building, 6th Floor","phone":"09 42 30 31 32","assignee":"Hana","contact_date":"2026-06-30","contacted":true}$json$::jsonb),
  (19, $json${"business_name":"The Cooking Studio","business_type":"Cooking Training","address":"Bole Dembel, Rayuma bldg","phone":"09 11 48 28 08/ 09 79 18 20 22","assignee":"Admas","contact_date":"2026-06-30","contacted":true,"note":"Couldn't meet the Chef Bini(owner) and ultimately forwarded to a receptionist. I explained everything for her. Planned to contact him again in-person and share him details through his phone(+251911482808)."}$json$::jsonb),
  (20, $json${"business_name":"LM International Hotel School","business_type":"Cooking Training","address":"5 kilo Almi Bldg 3rd Floor","phone":"09 43 33 33 33 / 09 43 44 44 44"}$json$::jsonb),
  (21, $json${"business_name":"Biruk Engineering","business_type":"Maintenance","phone":"09-42-22-95-22 / 09-30-00-79-97"}$json$::jsonb),
  (22, $json${"business_name":"DJ AB Decor","business_type":"Decor","address":"Bole Medhaniyalem, Selam City Mall","phone":"09 79 10 00 10","assignee":"Admas","contact_date":"2026-06-30","contacted":true,"note":"Met with a receptionist and explained it to her."}$json$::jsonb),
  (23, $json${"business_name":"Gold Addis Academy","business_type":"Decor","address":"Megenagna","phone":"09 46 05 77 46","assignee":"Hana","contact_date":"2026-06-30","point_of_contact":"reception: kidst","contacted":true,"note":"we'll let u know when we give orientation for our students"}$json$::jsonb),
  (24, $json${"business_name":"Beto finishing training center","business_type":"Finishing","address":"ጦርሃይሎች ኩዊንስ ሱፐርማርኬት ፊትለፊት","phone":"09 40 51 00 51"}$json$::jsonb),
  (25, $json${"business_name":"Peniel Training Institute","business_type":"General Skill Training","address":"Safari fyel bet Wul ena masreja building","phone":"0942 48 77 77 / 0942 58 77 77"}$json$::jsonb),
  (26, $json${"business_name":"IC Service Center","business_type":"Maintenance","address":"Megenagna, Metebaber Building, Office No 304","phone":"09 96 14 14 14","assignee":"Hana"}$json$::jsonb),
  (27, $json${"business_name":"Satcom Maintenance Training Institute","business_type":"Maintenance","address":"Megenagna","phone":"09 11 54 83 83","assignee":"Hana","contact_date":"2026-06-30","point_of_contact":"G/manager: haile","contacted":true,"note":"we'll inform our students about this and let u talk to them directly soon"}$json$::jsonb),
  (28, $json${"business_name":"SMB Mobile Repair Training Institute","business_type":"Maintenance","address":"Megenagna, Maraton Building, Office No 612","phone":"09 32 28  66 67","assignee":"Hana","point_of_contact":"manager: Samuel","contacted":true,"note":"I'll distribute this flyers for our students"}$json$::jsonb),
  (29, $json${"business_name":"Sage Training Institute","business_type":"Maintenance","address":"Megenagna Tamegas bldg 2nd floor","phone":"0906 7777 55"}$json$::jsonb),
  (30, $json${"business_name":"DIPCOM Technology Solutions","business_type":"Maintenance","address":"Lancha Husen Bldg ground floor","phone":"09 49 80 49 49"}$json$::jsonb),
  (31, $json${"business_name":"Positive Computer and mobile maintenance","business_type":"Maintenance","address":"Bethel Faris Bldg 1st Floor","phone":"09 61 33 73 74/ 07 14 63 74 73"}$json$::jsonb),
  (32, $json${"business_name":"EMD Cons finishing & Training","business_type":"Maintenance","address":"Around British Embassy","phone":"09 39 62 62 62 / 09 30 63 63 63"}$json$::jsonb),
  (33, $json${"business_name":"ZBinary","business_type":"Maintenance","phone":"09-42-22-95-22 / 09-30-00-79-97"}$json$::jsonb),
  (34, $json${"business_name":"Ris Technology Solution","business_type":"Maintenance","phone":"0974-272036 / 0925 759681"}$json$::jsonb),
  (35, $json${"business_name":"Biruk Engineering","business_type":"Maintenance","phone":"0942-22-9522 / 0930-00-7997"}$json$::jsonb),
  (36, $json${"business_name":"Yo Tech Security Solution","business_type":"Maintenance","address":"\"ቦሌ መድሕኒአለም ሬድዋን ህንፃ አጠገብ ሉሲድ ፕላዛ 1ኛ ፎቅ"}$json$::jsonb),
  (37, $json${"business_name":"\"","business_type":"09 31 77 79 79","address":"30/06/2026"}$json$::jsonb),
  (38, $json${"business_name":"Bina °ኤሌክትሪክ Installation","business_type":"Maintenance","address":"don't have office","phone":"09 96 50 93 25 / 09 09 13 91 69"}$json$::jsonb),
  (39, $json${"business_name":"\"Active Movers & Packers"}$json$::jsonb),
  (40, $json${"business_name":"\"","business_type":"Mover","phone":"09 82 27 00 00"}$json$::jsonb),
  (41, $json${"business_name":"BET movers & packers","business_type":"Mover","phone":"09 79 66 66 11"}$json$::jsonb),
  (42, $json${"business_name":"Marda movers","business_type":"Mover","phone":"09 88 64 65 66"}$json$::jsonb),
  (43, $json${"business_name":"Mela packers&movers","business_type":"Mover","phone":"09 30 30 65 30"}$json$::jsonb),
  (44, $json${"business_name":"Family movers","business_type":"Mover","phone":"09 62 22 00 00"}$json$::jsonb),
  (45, $json${"business_name":"Pack Addis movers","business_type":"Mover","phone":"09 40 81 00 00"}$json$::jsonb),
  (46, $json${"business_name":"Fancy Pastry Academy","business_type":"Pastry","address":"Semit","phone":"09 65 36 34 34"}$json$::jsonb),
  (47, $json${"business_name":"Passion Cake Training","business_type":"Pastry","address":"Sarbet Vatican Embassy","phone":"09 15 03 84 88"}$json$::jsonb),
  (48, $json${"business_name":"Cake Land Academy","business_type":"Pastry","address":"Bethel","phone":"09 78 19 79 81"}$json$::jsonb),
  (49, $json${"business_name":"Eksina Sweets","business_type":"Pastry","address":"megenagna city mall","phone":"09 85 10 43 43","assignee":"Hana","contact_date":"2026-06-30","point_of_contact":"manager","contacted":true,"note":"i'll share this info with others"}$json$::jsonb),
  (50, $json${"business_name":"Shewit Pastry Academy","business_type":"Pastry","address":"Bole, Friendship, Edenya Plaza","phone":"09 65 07 09 09","assignee":"Admas","contact_date":"2026-06-30","contacted":true,"note":"Ms. Shewit was busy teaching students but told her about Zemen. She forwarded me to her receptionist, Nardos, who is also a graduate. Nardos tried to create an account but failed to do so. She used an iPhone 7 mobile. Observations while Nardos opens an account were uploading an ID photo up on registration took too much time, faced multiple rate-limiting errors up on signup, got an error that said \"failed to save provider data\"."}$json$::jsonb),
  (51, $json${"business_name":"Fancy Pastry Academy","business_type":"Pastry","address":"Semit","phone":"09 65 36 34 34"}$json$::jsonb),
  (52, $json${"business_name":"Saffron Pastry","business_type":"Pastry","address":"Aware Square  Infront of abisiniya bank","phone":"09 37 64 51 84"}$json$::jsonb),
  (53, $json${"business_name":"Grano institute of pastry","business_type":"Pastry","address":"Kebena","phone":"09 91 32 92 25"}$json$::jsonb),
  (54, $json${"business_name":"ACI Pastry School","business_type":"Pastry","address":"Piassa Benin Mosque, in front of Shoa Supermarket, Hulualem bldg 2nd floor.","phone":"0912685235/0911432140"}$json$::jsonb),
  (55, $json${"business_name":"Semur Pastry and Bakery School","business_type":"Pastry","address":"Bethel,sket bank bldg 3rd floor","phone":"09 11 10 86 95 / 09 82 30 30 32","assignee":"Hana","contact_date":"2026-07-01","point_of_contact":"owner: alemu","contacted":true,"note":"I'll distribute this flyers for our students"}$json$::jsonb),
  (56, $json${"business_name":"Conte Pastry","business_type":"Pastry","address":"Infront of Imperial Hotel","phone":"251966789630","assignee":"Admas","contact_date":"2026-06-30","contacted":true,"note":"I called as if I was looking for her service and told her I want to come to her office for the details. She immedietly began asking when will my program be"}$json$::jsonb),
  (57, $json${"business_name":"Truth cleaning","business_type":"Cleaning","phone":"919383822"}$json$::jsonb),
  (58, $json${"business_name":"Sunrise cleaning service","business_type":"Cleaning","phone":"0909255560 / 0945496105"}$json$::jsonb),
  (59, $json${"business_name":"Rohoboth cleaning service","business_type":"Cleaning","phone":"0919622822 / 0987059597 / 0987324267"}$json$::jsonb),
  (60, $json${"business_name":"ጃምቦ የፅዳት አገልግሎት","business_type":"Cleaning","phone":"09 29 28 28 28"}$json$::jsonb),
  (61, $json${"business_name":"\"Mela Cleaning Services"}$json$::jsonb),
  (62, $json${"business_name":"\"","business_type":"Cleaning","phone":"931313188"}$json$::jsonb),
  (63, $json${"business_name":"ethiocleaning service","business_type":"Cleaning","phone":"09 04 14 03 46"}$json$::jsonb),
  (64, $json${"business_name":"Bright cleaning services","business_type":"Cleaning","phone":"\"0977308800 / 0968570834"}$json$::jsonb),
  (65, $json${"business_name":"\""}$json$::jsonb),
  (66, $json${"business_name":"ቤተ-ዉበት የፅዳት አገልግሎት","business_type":"Cleaning","phone":"0964115555 / 0910372535"}$json$::jsonb),
  (67, $json${"business_name":"isofa cleaning","business_type":"Cleaning","phone":"941804089"}$json$::jsonb),
  (68, $json${"business_name":"ማራኪ አጠቃላይ ፅዳት","business_type":"Cleaning","phone":"955734576"}$json$::jsonb),
  (69, $json${"business_name":"clean &GreenEth","business_type":"Cleaning","phone":"987433888"}$json$::jsonb),
  (70, $json${"business_name":"Solyet Cleaning","business_type":"Cleaning","phone":"962515050"}$json$::jsonb),
  (71, $json${"business_name":"vita decor and school","business_type":"decor","address":"jemo 1,nedi bldg 4th floor","phone":"936245071","assignee":"Hana","contact_date":"2026-07-01","point_of_contact":"manager","contacted":true,"note":"acc created"}$json$::jsonb),
  (72, $json${"business_name":"meron grma decor training","business_type":"decor","address":"lebu,medhaniyalem fanela bldg 1st floor","phone":"947710634","assignee":"Hana","contact_date":"2026-07-01","point_of_contact":"manager","contacted":true,"note":"I'll check it"}$json$::jsonb),
  (73, $json${"business_name":"nayomi training institute","business_type":"catering","address":"jemo 1, nedi bldg 5th floor","phone":"968000373","assignee":"Hana","contact_date":"2026-07-01","point_of_contact":"manager: tomas","contacted":true,"note":"I'll distribute this flyers for our students and we'll create it as a company"}$json$::jsonb),
  (74, $json${"business_name":"tnsae beauty training institute","business_type":"makeup","are_trainers":true,"address":"jemo 1, nedi bldg 6th floor","phone":"921757636","assignee":"Hana","contact_date":"2026-07-01","point_of_contact":"reception: almaz","contacted":true,"note":"we'll inform our students about this"}$json$::jsonb),
  (75, $json${"business_name":"four season pastry and food institute","business_type":"catering","are_trainers":true,"address":"bethel","phone":"913005121","assignee":"Hana","contact_date":"2026-07-01","point_of_contact":"assistant","contacted":true,"note":"I'll pass this info to the owner"}$json$::jsonb),
  (76, $json${"business_name":"helen beauty training institute","business_type":"makeup","are_trainers":true,"address":"Mexico, k kare bldg 4th floor","phone":"913976920","assignee":"Hana","contact_date":"2026-07-01","point_of_contact":"manager : mulu","contacted":true,"note":"flayer distributed to their trainees and meeting scheduled for Fri 3/7/26"}$json$::jsonb),
  (77, $json${"business_name":"Top training institiute","business_type":"Maintenance","are_trainers":true,"address":"megenagna,metebaber bldg 4th floor","phone":"910317675","assignee":"Hana","contact_date":"2026-06-22","point_of_contact":"reception: melat"}$json$::jsonb);
